# -*- coding: utf-8 -*-
"""Metodos de aprendizaje supervisado.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gsCKjVC15-q-hYGAAZwJut66HXDPh9bj
"""

import pandas as pd
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score

data_url = "https://raw.githubusercontent.com/SrZombra/modelo-no-supervisado/refs/heads/main/dataset.csv"
data_base = pd.read_csv(data_url, sep=";")
data_base

encoder_tipo_parada = LabelEncoder()
data_base['Tipo_Parada'] = encoder_tipo_parada.fit_transform(data_base['Tipo_Parada']) # SITP → 0

encoder_hora_pico = LabelEncoder()
data_base['Hora_Pico'] = encoder_hora_pico.fit_transform(data_base['Hora_Pico'])

encoder_zona = LabelEncoder()
data_base['Zona'] = encoder_zona.fit_transform(data_base['Zona'])

#Definimos las caracteristicas y etiquetas
features = data_base[['Latitud', 'Longitud', 'Cantidad_Pasajeros', 'Hora_Pico', 'Promedio_Espera_Min', 'Zona']]
labels = data_base['Tipo_Parada']

scaler = StandardScaler()
features_scaled = scaler.fit_transform(features)

X_train, X_test, y_train, y_test = train_test_split(features_scaled, labels, test_size=0.2, random_state=42)

# 6. Entrenar el clasificador de Árbol de Decisión
classifier = tree.DecisionTreeClassifier(random_state=42)
classifier.fit(X_train, y_train)

new_data = pd.DataFrame([[40.61, -74.06, 195, 1, 1, 4]],
                          columns=['Latitud', 'Longitud', 'Cantidad_Pasajeros', 'Hora_Pico',
                                   'Promedio_Espera_Min', 'Zona'])

nuevo_dato_scaled = scaler.transform(new_data)  # Escalar los datos nuevos
prediccion = classifier.predict(nuevo_dato_scaled)
print(f'Tipo de parada predicho: {encoder_tipo_parada.inverse_transform(prediccion)[0]}')